ollama:
  gpu:
    # -- Enable GPU integration
    enabled: true

    # -- GPU type: 'nvidia' or 'amd'
    type: 'nvidia'

    # -- Specify the number of GPU to 2
    number: 1

  # -- List of models to pull at container startup
  models:
    - mistral
    - starcoder2:7b
ingress:
  enabled: true
  hosts:
    - host: ollama.local
      paths:
        - path: /
          pathType: Prefix
